services:
  frontend:
    container_name: website
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
    restart:  always

