services:
  frontend:
    container_name: website
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - ${PORT}:3000
    environment:
      - NODE_ENV=production
    restart:  always

